language: node_js

os:
  - linux
  - osx

sudo: false

node_js:
  - 12
  - 11
  - 10
  - 9
  - 8

install:
  - npm install
  - npm install -g codecov

script:
  - node app.js
  - codecov
  
branches:
  only:
    - master
